GO := /usr/local/bin/go
GCC := /usr/bin/gcc
.PHONY: *

build-goc:
	@$(GO) build -buildmode=c-shared -o ../../build/group_sort.so .

test-goc:
	@$(GO) test -v -race -timeout 5s ./...

build-cpp:
	@$(GCC) sort-group.cpp -shared -o ../../build/sort_group.so -g -fPIC -fvisibility=hidden

.DEFAULT_GOAL := build-goc